language: java
jdk: oraclejdk8
sudo : false
branches:
  only:
  - master
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS xcolab;'
  - sh $TRAVIS_BUILD_DIR/scripts/travis/before_script.sh
install:
  - sh $TRAVIS_BUILD_DIR/scripts/travis/deploy.sh
