language: java
jdk: oraclejdk8
sudo : false
branches:
  only:
  - master
services:
  - mysql
cache:                                                                          
  directories:                                                                  
    - $HOME/.m2    
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS xcolab;'
  - sh $TRAVIS_BUILD_DIR/scripts/travis/before_script.sh
install : true
script:
  - sh $TRAVIS_BUILD_DIR/scripts/travis/deploy.sh
after_success:
  - sh $TRAVIS_BUILD_DIR/scripts/travis/before_script.sh
  - ls $TRAVIS_BUILD_DIR/deploy/
deploy:
  -
  - provider: s3
     access_key_id: "$AWS_KEY_ID"
     secret_access_key: "$AWS_PASSWORD"
     bucket: "colabbucket"
     key: "ColabBinaries"
     skip_cleanup: true
     local-dir: "$TRAVIS_BUILD_DIR/deploy"
