language: java
jdk: oraclejdk8
sudo : false
branches:
  only:
  - master
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS xcolab;'
before_script: /script/travis/before_script.sh

